version : '3.2'

services:
  db:
    image: mysql:8.0
    mem_limit: 500m
    ports:
      - "3306:3306"
    volumes:
      - ./mysqlBackup:/var/lib/mysql
    networks:
      - arya-docker-network
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      

networks:
  arya-docker-network:
    external: true